version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      github-actions-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]
      github-actions-major:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["major"]
    open-pull-requests-limit: 1
